import yaml
import os
import boto3
from botocore.exceptions import ClientError

class EasyIAMManager:
    def __init__(self, session, spec_path):
        self.session = session
        self.spec_path = spec_path
        self.iam = session.client('iam')
        with open(spec_path, 'r') as f:
            self.spec = yaml.safe_load(f)

    # --- PART 1: The Generator (Simplifies CloudFormation) ---
    def generate_cloudformation(self, output_path):
        """
        Reads the Simple Spec and writes a complex CloudFormation file.
        """
        print(f"Generating CloudFormation from {self.spec_path}...")
        
        # 1. Start the Template
        template = {
            "AWSTemplateFormatVersion": "2010-09-09",
            "Description": "Generated by AWS Easy Manager",
            "Resources": {},
            "Outputs": {}
        }

        # 2. Add Groups
        # We need a map to specific AWS ARNs for common permissions
        PERMISSION_MAP = {
            'S3FullAccess': 'arn:aws:iam::aws:policy/AmazonS3FullAccess',
            'EC2ReadOnly': 'arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess',
            'Billing': 'arn:aws:iam::aws:policy/job-function/Billing',
            'Admin': 'arn:aws:iam::aws:policy/AdministratorAccess'
        }

        for group in self.spec['groups']:
            group_name = group['name']
            
            # Map friendly names to ARNs
            policies = []
            for perm in group['permissions']:
                if perm in PERMISSION_MAP:
                    policies.append(PERMISSION_MAP[perm])
                else:
                    print(f"WARNING: Unknown permission '{perm}'. Skipping.")

            # Create Group Resource
            template['Resources'][f"Group{group_name}"] = {
                "Type": "AWS::IAM::Group",
                "Properties": {
                    "GroupName": group_name,
                    "ManagedPolicyArns": policies
                }
            }

        # 3. Add Users
        for user in self.spec['users']:
            user_name = user['name']
            group_name = user['group']
            
            # Create User Resource
            template['Resources'][f"User{user_name}"] = {
                "Type": "AWS::IAM::User",
                "Properties": {
                    "UserName": user_name,
                    "Groups": [{"Ref": f"Group{group_name}"}],
                    "ManagedPolicyArns": [
                        "arn:aws:iam::aws:policy/IAMUserChangePassword"
                    ]
                }
            }

            # Add Output for Login URL
            template['Outputs'][f"{user_name}ConsoleLink"] = {
                "Description": f"Login link for {user_name}",
                "Value": { "Fn::Sub": f"https://${{AWS::AccountId}}.signin.aws.amazon.com/console" }
            }

        # 4. Write to File
        with open(output_path, 'w') as f:
            # Check if file exists to avoid overwrite error if we were appending (we are writing fresh)
            pass 
        
        # We use a custom dumper logic or a library to write clean YAML
        # But standard yaml.dump is sufficient for CloudFormation
        with open(output_path, 'w') as f:
            yaml.dump(template, f, default_flow_style=False)
        
        print(f"Success: Generated {output_path}")

    # --- PART 2: The Onboarder (Simplifies Password Management) ---
    def onboard_users(self):
        """
        Sets passwords for new users and prints "Welcome Emails".
        """
        print("\n--- ONBOARDING REPORT ---")
        
        default_password = self.spec['config']['default_password']
        account_id = self.session.client('sts').get_caller_identity()['Account']

        for user in self.spec['users']:
            user_name = user['name']
            email = user.get('email', 'N/A')
            
            # Check if user needs a password
            if not self._user_has_login_profile(user_name):
                print(f"[*] Setting initial password for {user_name}...")
                self._create_login_profile(user_name, default_password)
                
                # Print Welcome Kit (Backup)
                print(f"\n[EMAIL CONTENT FOR {user_name}]")
                print("-" * 40)
                print(f"TO: {email}")
                print(f"Login URL: https://{account_id}.signin.aws.amazon.com/console")
                print(f"Username: {user_name}")
                print(f"Password: {default_password}")
                print("-" * 40)

                # Send Real Email via SES
                self._send_welcome_email(user_name, email, default_password, account_id)

            else:
                print(f"[OK] User {user_name} already has a password.")

    def _send_welcome_email(self, user_name, email, password, account_id):
        """
        Sends the credentials via AWS SES.
        """
        ses = self.session.client('ses')
        SENDER = "sean.girgis@gmail.com" # Must be verified in SES
        
        try:
            print(f"[*] Sending email to {email}...")
            ses.send_email(
                Source=SENDER,
                Destination={'ToAddresses': [email]},
                Message={
                    'Subject': {'Data': "Welcome to AWS - Your Credentials"},
                    'Body': {
                        'Text': {
                            'Data': f"""
Hello {user_name},

Your AWS account has been created.

Login URL: https://{account_id}.signin.aws.amazon.com/console
Username: {user_name}
Password: {password}

Please change this password immediately upon login.
                            """
                        }
                    }
                }
            )
            print(f"[SUCCESS] Email sent to {email}")
        except ClientError as e:
            print(f"[ERROR] Could not send email: {e}")
            print(f"Tip: In Sandbox mode, both '{SENDER}' AND '{email}' must be verified.")

    def _user_has_login_profile(self, user_name):
        try:
            self.iam.get_login_profile(UserName=user_name)
            return True
        except ClientError as e:
            if "NoSuchEntity" in str(e):
                return False # User exists but no password
            # If user doesn't exist at all yet (maybe stack failed), return True to skip
            return True 

    def _create_login_profile(self, user_name, password):
        try:
            self.iam.create_login_profile(
                UserName=user_name,
                Password=password,
                PasswordResetRequired=True
            )
        except ClientError as e:
            print(f"Error setting password for {user_name}: {e}")
